<a href="https://www.kaggle.com/code/timothyokoroafor001/sleep-health-lifestyle-analysis?scriptVersionId=247541438" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from pandasql import sqldf
from IPython.display import display
import plotly.express as px
import plotly.graph_objects as go
import plotly.graph_objects as go
from plotly.offline import iplot
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sleep-health-and-lifestyle-dataset/Sleep_health_and_lifestyle_dataset.csv

In [2]:
file_path = "/kaggle/input/sleep-health-and-lifestyle-dataset/Sleep_health_and_lifestyle_dataset.csv"
df = pd.read_csv(file_path)

In [3]:
init_notebook_mode(connected=True)

In [4]:
query = """
    SELECT `Occupation`, `Sleep Duration`, `Quality of Sleep`
    FROM df;
"""

# Execute the query
sleep_by_occupation = sqldf(query, globals())  # 'globals()' makes 'df' available in SQL
display(sleep_by_occupation) # Display results

               Occupation  Sleep Duration  Quality of Sleep
0       Software Engineer             6.1                 6
1                  Doctor             6.2                 6
2                  Doctor             6.2                 6
3    Sales Representative             5.9                 4
4    Sales Representative             5.9                 4
..                    ...             ...               ...
369                 Nurse             8.1                 9
370                 Nurse             8.0                 9
371                 Nurse             8.1                 9
372                 Nurse             8.1                 9
373                 Nurse             8.1                 9

[374 rows x 3 columns]

In [5]:
import plotly.express as px

fig = px.scatter(
    sleep_by_occupation,
    x='Sleep Duration',
    y='Quality of Sleep',
    color='Occupation',
    title='Sleep Duration vs Quality of Sleep by Occupation',
    labels={
        'Sleep Duration': 'Sleep Duration (hours)',
        'Quality of Sleep': 'Quality of Sleep (1-10)'
    },
    height=600
)

fig.show(renderer='iframe')

In [6]:
query = """
    select `occupation`,`Physical Activity Level` as pal, `stress level`
    FROM df;
"""

# Execute the query
sleep_by_stress = sqldf(query, globals())  # 'globals()' makes 'df' available in SQL
display(sleep_by_stress)  # Display results

               Occupation  pal  Stress Level
0       Software Engineer   42             6
1                  Doctor   60             8
2                  Doctor   60             8
3    Sales Representative   30             8
4    Sales Representative   30             8
..                    ...  ...           ...
369                 Nurse   75             3
370                 Nurse   75             3
371                 Nurse   75             3
372                 Nurse   75             3
373                 Nurse   75             3

[374 rows x 3 columns]

In [7]:
fig2 = px.bar(sleep_by_stress, 
              x='Occupation', 
              y='pal', 
              color='Stress Level',
              title='Physical Activity Level by Occupation with Stress Level',
              labels={'pal': 'Physical Activity Level (minutes/day)'},
              barmode='group')
fig2.update_layout(height=600, xaxis={'categoryorder':'total descending'})
fig2.show(renderer='iframe')

In [8]:
query= """
select Occupation, `Sleep Disorder`
from df;
"""
quality_of_sleep = sqldf(query, globals())
display(quality_of_sleep)  # Display results

               Occupation Sleep Disorder
0       Software Engineer           None
1                  Doctor           None
2                  Doctor           None
3    Sales Representative    Sleep Apnea
4    Sales Representative    Sleep Apnea
..                    ...            ...
369                 Nurse    Sleep Apnea
370                 Nurse    Sleep Apnea
371                 Nurse    Sleep Apnea
372                 Nurse    Sleep Apnea
373                 Nurse    Sleep Apnea

[374 rows x 2 columns]

In [9]:
query= """
select `BMI Category`, `Blood Pressure`, `Sleep Duration`
from df;
"""
result4 = sqldf(query, globals())
display(result4)  # Display results

    BMI Category Blood Pressure  Sleep Duration
0     Overweight         126/83             6.1
1         Normal         125/80             6.2
2         Normal         125/80             6.2
3          Obese         140/90             5.9
4          Obese         140/90             5.9
..           ...            ...             ...
369   Overweight         140/95             8.1
370   Overweight         140/95             8.0
371   Overweight         140/95             8.1
372   Overweight         140/95             8.1
373   Overweight         140/95             8.1

[374 rows x 3 columns]

In [10]:
fig4 = px.box(
    result4,
    x="BMI Category",
    y="Sleep Duration",
    color="Blood Pressure",  # Only works if Blood Pressure is categorical
    title="Sleep Duration by BMI Category & Blood Pressure",
    labels={"Sleep Duration": "Sleep Duration (hours)"},
)
fig4.update_layout(height=600)
fig4.show(renderer="iframe")

In [11]:
query = """
SELECT 
    `Occupation`, 
    AVG(`Stress Level`) AS 'Stress Level',
    AVG(`Blood Pressure`) AS 'Avg Blood Pressure',
    COUNT(*) AS 'Count'
FROM df
GROUP BY `Occupation`
"""
result5 = sqldf(query, globals())
display(result5)

              Occupation  Stress Level  Avg Blood Pressure  Count
0             Accountant      4.594595          117.729730     37
1                 Doctor      6.732394          123.000000     71
2               Engineer      3.888889          125.904762     63
3                 Lawyer      5.063830          129.957447     47
4                Manager      5.000000          125.000000      1
5                  Nurse      5.547945          138.520548     73
6   Sales Representative      8.000000          140.000000      2
7            Salesperson      7.000000          130.000000     32
8              Scientist      7.000000          129.500000      4
9      Software Engineer      6.000000          126.500000      4
10               Teacher      4.525000          131.225000     40

In [12]:
fig5 = px.scatter(
    result5,
    x='Stress Level',
    y='Avg Blood Pressure',
    size='Count',
    color='Occupation',
    title='Stress Level vs Blood Pressure by Occupation',
    labels={
        'Avg Blood Pressure': 'Avg Blood Pressure (mmHg)',
        'Stress Level': 'Stress Level (1-10)'
    },
    hover_data=['Occupation', 'Avg Blood Pressure', 'Stress Level', 'Count']
)
fig5.update_layout(height=600)
fig5.show(renderer='iframe')